# Configuração de financiamento do projeto
# Você pode adicionar suas opções de financiamento aqui

# github: [ParkNow914]
# patreon: # seu usuário
# ko_fi: # seu usuário
# custom: ['https://www.paypal.me/seupaypal']
