# Estágio de desenvolvimento
FROM node:18-alpine

# Define o diretório de trabalho
WORKDIR /app

# Instala dependências de desenvolvimento
RUN apk add --no-cache \
    git \
    curl \
    python3 \
    make \
    g++

# Copia os arquivos de definição de dependências
COPY package*.json ./
COPY yarn.lock ./

# Instala as dependências
RUN npm install

# Copia o restante do código-fonte
COPY . .

# Expõe a porta da aplicação
EXPOSE 3000

# Comando para iniciar a aplicação em desenvolvimento
CMD ["npm", "run", "dev"]
